on:
  workflow_call:
jobs:
  job1:
    uses: ./.github/workflows/hello-world.yml
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "job2"
  job3:
    needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
      - run: echo "job3"
